# Generated by Django 4.1.3 on 2022-11-07 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='reservation.listing'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='reservation.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'reserved_from_date')},
        ),
    ]
